# --- CONFIGURACIÓN DE ATENEA (Tus datos reales) ---
API_ID = '25010667'
API_HASH = '1f1e310034a2e5d506d194c798030f00'
BOT_TOKEN = '8589259671:AAFhRp4tLKtl9LeWoa4uWt1dbBsL7J0GHsM'  # <-- Pega aquí el token que te dio BotFather

# Google AI / Atenea
GEMINI_KEY = "AIzaSyBvdZun08h7sjwrLUtmWZ5s475IY5ekEi0"
MODEL_NAME = "gemini-1.5-flash-latest"

PROJECT_NAME = "ATENEA PROYECT"
AGENT_NAME = "ATENEA AGENT"